server:
  servlet:
    context-path: /api/instalite/v1.0
  port: 8080
  address: localhost

spring:
  jpa:
    database: MYSQL
    hibernate:
      format-sql: true
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/instalite_db
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

logging:
  level:
    root: INFO
    com:
      instalite: TRACE
